version: "3"

services:
  db:
    image: mysql:5.7
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: pokeagenda
    network_mode: host