spring:
  application.name: pokeagenda
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:mysql://localhost:3306/pokeagenda?useSSL=false'
    username: 'root'
    password: 'toor'
    type: 'com.zaxxer.hikari.HikariDataSource'
    driver-class-name: 'com.mysql.jdbc.Driver'
    hikari:
      pool-name: 'pokeagenda'
      connection-timeout: 6000
      minimum-idle: 1
      maximum-pool-size: 35
      connection-init-sql: SELECT 1
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: 'org.hibernate.dialect.MySQL57InnoDBDialect'
    hibernate:
      show-sql: true
    properties:
      hibernate.format_sql: true